### ISSUE TITLE
Add fallback redirects to docs.ros.org/api

### ISSUE THREAD

**Issue by mikepurvis** [ros-infrastructure/ros.org_scripts#5]
The following config placed in an `.htaccess` file in the docs root should maintain the existing behaviour (symlink to current distro) while also falling back to a redirect for prior distros, if the file is found:

```
RewriteEngine on
RewriteBase /

RewriteCond %{DOCUMENT_ROOT}/jade/$0 -d [OR]
RewriteCond %{DOCUMENT_ROOT}/jade/$0 -f
RewriteRule ^api/.*$ /jade/$0

RewriteCond %{DOCUMENT_ROOT}/indigo/$0 -d [OR]
RewriteCond %{DOCUMENT_ROOT}/indigo/$0 -f
RewriteRule ^api/.*$ /indigo/$0 [R=302]

RewriteCond %{DOCUMENT_ROOT}/hydro/$0 -d [OR]
RewriteCond %{DOCUMENT_ROOT}/hydro/$0 -f
RewriteRule ^api/.*$ /hydro/$0 [R=302]

RewriteCond %{DOCUMENT_ROOT}/groovy/$0 -d [OR]
RewriteCond %{DOCUMENT_ROOT}/groovy/$0 -f
RewriteRule ^api/.*$ /groovy/$0 [R=302]
```

Note that the fallback is based on files existing rather than package paths existing, so it's possible to imagine that a change might be made in Jade which eliminates a source file, and someone attempting to consult documentation could find themselves mistakenly redirected back to the Indigo version of the docs. I don't think this is a high risk, but it's work being aware of.

A potential modification to this would be to make the current distro a redirection as well, rather than symlink. I don't have strong feelings on this one way or the other.

@dirk-thomas to review.

EDIT: Fix to properly detect existence of files as well as directories.

**Comment by tfoote** [comment]
I don't think that we should just fallback to the previous version if
you've called out a version. I think a better approach might be a dynamic
404 page which can find other verisons and suggest following up on them.

For the LTS issue I think that maybe having an lts symlink for the latest
lts distro might make sense.

**Comment by mikepurvis** [comment]
This doesn't fall back if you specify a version in the URL— this only redirects/rewrites URLs which start with `docs.ros.org/api`. Per the example given on the mailing list discussion, under this scheme,

`http://docs.ros.org/api/roscpp/html/` displays the contents of `http://docs.ros.org/jade/api/roscpp/html/`

But

`http://docs.ros.org/api/hardware_interface/html/` is a 302 temporary redirect to `http://docs.ros.org/indigo/api/hardware_interface/html/` (until ros_control is released for Jade)

But visiting `http://docs.ros.org/jade/api/hardware_interface/html/` will still give you a 404.

**Comment by dirk-thomas** [comment]
I would prefer to place the `.htaccess` file in the `api` folder to keep it local to URLs it is supposed to modify. But it should be easy to adapt.

Thank you @mikepurvis I will try it on the server soon.

**Comment by dirk-thomas** [comment]
I am waiting for OSUOSL to modify the Apache configuration to allow mod_rewrite rules in the `.htaccess` file.

In general I think a single `api` folder with whatever behavior does not address all the needs mentioned above. I would propose the following:
- a symlink `latest` which points to the latest ROS distribution (currently _Jade_)
- a symlink `latest-lts` which points to the latest LTS ROS distribution (currently _Indigo_)
- a folder `latest-available` which uses `mod_rewrite` to redirect the client to the latest ROS distribution which contains the resource specified behind the prefix `latest-available`
- eventually a folder `latest-lts-available` also using `mod_rewrite`

All of the above are not specific to the `api` subfolder but can be used for the `changelogs` and `tags` as well.

**Comment by dirk-thomas** [comment]
The .htaccess file works now. I created the symlinks and redirects from my previous comment:
- http://docs.ros.org/latest/
- http://docs.ros.org/latest-lts/
- http://docs.ros.org/latest-available/api/abb/

Does that address the needs from this ticket?

**Comment by mikepurvis** [comment]
Yup, that's perfect. Thanks.

**Comment by mikepurvis** [comment]
@dirk-thomas This should be updated for Kinetic.

**Comment by dirk-thomas** [comment]
@jacquelinekay Can you please take care of this for Kinetic and also add it to the todo list for the next release.
